In [17]:
import numpy as np
world_alcohol = np.genfromtxt("original.csv",delimiter=",",dtype="U75"  )
world_alcohol
df = np.genfromtxt("original.csv",delimiter=",",skip_header=1 )


In [15]:
df.dtype

dtype('float64')

Comparaison :


In [3]:
vector = np.array([5,10,6,20])

In [4]:
vector ==10

array([False,  True, False, False])

In [7]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [21]:
 #la 3e colonne : 
contries_canada=world_alcohol[:,2]=="Canada"
contries_canada

array([False, False, False, ..., False, False, False])

In [22]:
years_1984=world_alcohol[:,0]=="1984"
years_1984

array([False, False, False, ..., False, False, False])

 Sélectionner des éléments

In [6]:
vector = np.array([5,10,6,20])
equal_to_ten = (vector ==10)
print(vector[equal_to_ten])
vector

[10]


array([ 5, 10,  6, 20])

On affiche uniquement les champs qui contiennent notre condition (selection )

In [24]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
second_column_25= (matrix[:,1]==25)
print(matrix[second_column_25,:])

[[20 25 30]]


On retourne la ligne qui contient 25 dans la premiere colonne de la matrice 

In [29]:
#COMPARAISON DE LA 3e COLONNE A LA CHAINE "Algeria"
country_is_algeria=world_alcohol[:,2]=="Algeria"

In [9]:
#SELECTION DES LIGNES QUI CONTIENNT LA CHAINE "Algeria"
#country_algeria= world_alcohol[country_is_algeria,:]
#country_algeria

country_algeria_2= world_alcohol[world_alcohol[:,2]=="Algeria"]
country_algeria_2

array([['1984', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1987', 'Africa', 'Algeria', 'Beer', '0.17'],
       ['1987', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1984', 'Africa', 'Algeria', 'Other', '0'],
       ['1989', 'Africa', 'Algeria', 'Beer', '0.16'],
       ['1989', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1989', 'Africa', 'Algeria', 'Wine', '0.23'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1984', 'Africa', 'Algeria', 'Wine', '0.12'],
       ['1985', 'Africa', 'Algeria', 'Beer', '0.19'],
       ['1985', 'Africa', 'Algeria', 'Other', '0'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1985', 'Africa', 'Algeria', 'Wine', '0.11'],
       ['1986', 'Africa', 'Algeria', 'Other', '0'],
       ['1989', 'Africa', 'Algeria', 'Other', '0'],
       ['1987', 'Africa', 'Algeria', 'Other', '0'],
       ['1984', 'Africa', 'Algeria', 'Beer', '0.2'],
       ['1985', 'Africa', 'A

In [32]:
#FAIRE PARIELLE POUR LA L'ANNEE "1984"
years_is_1984 = (world_alcohol[:,0]=="1984")
years_1984 = world_alcohol[years_is_1984,:]
years_1984

array([['1984', 'Africa', 'Nigeria', 'Other', '6.1'],
       ['1984', 'Eastern Mediterranean', 'Afghanistan', 'Other', '0'],
       ['1984', 'Americas', 'Costa Rica', 'Wine', '0.06'],
       ...,
       ['1984', 'Europe', 'Latvia', 'Spirits', '7.5'],
       ['1984', 'Africa', 'Angola', 'Wine', '0.57'],
       ['1984', 'Africa', 'Central African Republic', 'Wine', '0.46']],
      dtype='<U75')

In [35]:
##Plus rapide 
years_1984 = world_alcohol[world_alcohol[:,0]=="1984"]
years_1984

array([['1984', 'Africa', 'Nigeria', 'Other', '6.1'],
       ['1984', 'Eastern Mediterranean', 'Afghanistan', 'Other', '0'],
       ['1984', 'Americas', 'Costa Rica', 'Wine', '0.06'],
       ...,
       ['1984', 'Europe', 'Latvia', 'Spirits', '7.5'],
       ['1984', 'Africa', 'Angola', 'Wine', '0.57'],
       ['1984', 'Africa', 'Central African Republic', 'Wine', '0.46']],
      dtype='<U75')

Effectuer des comparaisons avec plusieurs conditions

In [36]:
vector

array([ 5, 10,  6, 20])

In [45]:
equal_to_ten_and_five = (vector == 10) & (vector == 5)
equal_to_ten_and_five

array([False, False, False, False])

In [46]:
equal_to_ten_or_five= (vector == 10) | (vector == 5)
equal_to_ten_or_five

array([ True,  True, False, False])

selectionner les lignes correspondantes à algeria et 1986

In [57]:
algeria = world_alcohol[world_alcohol[:,2]=="Algeria",:]
algeria_and_1986 = algeria[algeria[:,0]=="1986",:]
algeria_and_1986 

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1986', 'Africa', 'Algeria', 'Other', '0']], dtype='<U75')

Une deuxieme syntaxe (plus rapide) :

In [10]:
algeria_and_1986 = world_alcohol[(world_alcohol[:,2]=="Algeria")&(world_alcohol[:,0]=="1986")]
algeria_and_1986
#il ne faut jamais oublier les parantheses qu'on fait des comparaisons 

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1986', 'Africa', 'Algeria', 'Other', '0']], dtype='<U75')

Remplacer des valeurs dans un tableau Numpy

In [61]:
vector

array([ 5, 10,  6, 20])

In [65]:
equal_to_ten_or_five = (vector==10)|(vector==5)
equal_to_ten_or_five

array([ True,  True, False, False])

In [67]:
vector[equal_to_ten_or_five]= 50
vector

array([50, 50,  6, 20])

In [68]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
second_colum_25 = matrix[:,1]==25
print(second_colum_25)

[False  True False]


In [70]:
matrix[second_colum_25,1]=10
matrix

array([[ 5, 10, 15],
       [20, 10, 30],
       [35, 40, 45]])

In [71]:
world_alcohol_2 = world_alcohol

Rempalcer toutes les années "1986" de la premiere colonne de world_alcohol_2 par "2018"

In [86]:
world_alcohol_2[:,0][world_alcohol_2[:,0]=="1986"]="2018"
#sélection de la première colonne du tableau puis on ajoute
#une condition de sélection [world_alcohol_2[:, 0] == "1986"].
#same thing like where world_alcohol_2[:,0]=="1986"

Remplacer toutes les alcools "Wine" de la 4e colonne de world_alacohol par "Beer"

In [78]:
world_alcohol_2[:,3][world_alcohol_2[:,3]=="Wine"]="Beer"

In [84]:
 print(world_alcohol_2)

[['2018' 'Western Pacific' 'Viet Nam' 'Beer' '0']
 ['2018' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Beer' '1.62']
 ...
 ['2018' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['2018' 'Africa' 'Swaziland' 'Other' '5.15']]


In [83]:
 world_alcohol

array([['2018', 'Western Pacific', 'Viet Nam', 'Beer', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Beer', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

Une deuxieme syntaxe  :

In [89]:
world_alcohol_2[world_alcohol_2[:,0]=="1986",0]="2018"
# ndarray[condition, première colonne] donc tableau sur lequel 
#on sélectionne seulement les valeurs "1986" de la première colonne

Remplacer les chaines de caractères vides

On ne peut pas realiser des operation mathematique sur des chaines de charachteres, pour resoudre ce probleme on doit les transformer en nombres : 

In [113]:
is_value_empty = world_alcohol_2[:,4]==""
world_alcohol_2[is_value_empty,4]="0"
world_alcohol_2

array([['2018', 'Western Pacific', 'Viet Nam', 'Beer', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Beer', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [117]:
np.random.seed(42)

a = np.random.randn(3, 4)
a[2][2] = np.nan
print (a)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004         nan -0.46572975]]


In [128]:
np.savetxt('np.csv', world_alcohol_2,fmt='%s', delimiter=',')

# Convertir des types de données

In [129]:
# astype()

In [130]:
vector = np.array(["1","2","3"])

In [132]:
vector= vector.astype(float)

In [133]:
vector

array([1., 2., 3.])

In [134]:
alcohol_consumption = world_alcohol[:,4]

In [136]:
alcohol_consumption=alcohol_consumption.astype(float)
print(alcohol_consumption)

[0.   0.5  1.62 ... 2.54 0.   5.15]


# Réaliser des calcules mathématiques avec Numpy

In [137]:
#sum()
#mean()
#max()

In [138]:
vector = np.array([5,10,15,20])

In [142]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [143]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [146]:
#axis = 1  ==> lignes
matrix.sum(axis=1 )

array([ 30,  75, 120])

In [147]:
#axis = 0  ==> colonnes
matrix.sum(axis=0 )

array([60, 75, 90])

calculer la somme des valeurs de alcool_consumption 

In [148]:
total_alcohol = alcohol_consumption.sum()

calculer la moyen des valeurs de alcool_consumption

In [149]:
average_alcohol = alcohol_consumption.mean()

In [154]:
print(total_alcohol)
print(average_alcohol )
 

3908.96
1.2001719373656738


In [157]:
print("verification : ",total_alcohol/len(alcohol_consumption))

verification :  1.2001719373656738


### Calculer la consommation totale annuelle par habitant pour "Canada" en 1986

In [158]:
print(world_alcohol[world_alcohol[:,2]=="Canada"])

[['1984' 'Americas' 'Canada' 'Spirits' '3.35']
 ['1989' 'Americas' 'Canada' 'Beer' '1.27']
 ['1984' 'Americas' 'Canada' 'Beer' '5']
 ['1985' 'Americas' 'Canada' 'Beer' '4.94']
 ['1987' 'Americas' 'Canada' 'Beer' '1.3']
 ['1987' 'Americas' 'Canada' 'Beer' '4.83']
 ['2018' 'Americas' 'Canada' 'Other' '0']
 ['2018' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1985' 'Americas' 'Canada' 'Spirits' '3.21']
 ['1985' 'Americas' 'Canada' 'Other' '0']
 ['2018' 'Americas' 'Canada' 'Beer' '4.87']
 ['1984' 'Americas' 'Canada' 'Beer' '1.24']
 ['1989' 'Americas' 'Canada' 'Spirits' '2.91']
 ['1984' 'Americas' 'Canada' 'Other' '0']
 ['1985' 'Americas' 'Canada' 'Beer' '1.29']
 ['1987' 'Americas' 'Canada' 'Spirits' '2.99']
 ['1989' 'Americas' 'Canada' 'Beer' '4.82']
 ['1989' 'Americas' 'Canada' 'Other' '0']
 ['2018' 'Americas' 'Canada' 'Beer' '1.33']
 ['1987' 'Americas' 'Canada' 'Other' '0']]


In [42]:
 canada_1986= world_alcohol[(world_alcohol[:,2]=="Canada")&(world_alcohol[:,0]=="1986")]

In [43]:
canada_1986  

array([['1986', 'Americas', 'Canada', 'Other', ''],
       ['1986', 'Americas', 'Canada', 'Spirits', '3.11'],
       ['1986', 'Americas', 'Canada', 'Beer', '4.87'],
       ['1986', 'Americas', 'Canada', 'Wine', '1.33']], dtype='<U75')

In [45]:
#rempalacer tout string vide par 0, et transformer en float 
canada_alcohol = canada_1986[:,4]
canada_alcohol[canada_alcohol==""]=0
canada_alcohol=canada_alcohol.astype(float)

In [46]:
total_canadien_drinking = canada_alcohol.sum()

In [47]:
total_canadien_drinking

9.31

# Calculer la consommation pour chaque pays à l'annee 1989

In [194]:
totals = {}

In [214]:
year = world_alcohol[world_alcohol[:,0]=="1989"]
year

array([['1989', 'Americas', 'Guatemala', 'Beer', '0.62'],
       ['1989', 'Africa', 'Seychelles', 'Beer', '2.23'],
       ['1989', 'Americas', 'Costa Rica', 'Spirits', '4.51'],
       ...,
       ['1989', 'Eastern Mediterranean', 'Morocco', 'Spirits', '0.07'],
       ['1989', 'Europe', 'Poland', 'Beer', '2.03'],
       ['1989', 'Europe', 'Turkey', 'Other', '0']], dtype='<U75')

In [52]:
contries = set(world_alcohol[:,2])
#set() => Get unique values from a list
 

In [216]:
for pays in contries :
 contrey_consumption = year[year[:,2]==pays]
 colonne_5 = contrey_consumption[:,4]
 colonne_5[colonne_5==""]=0
 colonne_5=colonne_5.astype(float)
 sum_pays = colonne_5.sum()
 totals[pays]=sum_pays

In [222]:
for pays in totals:
    print(pays,"=>", totals[pays])

United States of America => 9.16
Djibouti => 0.87
Romania => 8.41
Turkey => 0.72
Chile => 8.649999999999999
Uruguay => 7.4399999999999995
Saudi Arabia => 0.15
Gabon => 9.34
Japan => 7.74
Iraq => 0.75
Indonesia => 0.07
France => 16.05
Norway => 5.08
Latvia => 7.039999999999999
Belgium => 11.61
Italy => 10.899999999999999
Micronesia (Federated States of) => 0.0
United Republic of Tanzania => 5.9
El Salvador => 1.77
Poland => 9.33
Chad => 0.30000000000000004
Democratic Republic of the Congo => 1.92
Mauritius => 3.54
Trinidad and Tobago => 4.68
Cabo Verde => 2.79
Oman => 1.03
Netherlands => 10.030000000000001
Portugal => 15.350000000000001
Solomon Islands => 0.5800000000000001
Viet Nam => 0.16
Lesotho => 2.02
Liberia => 5.61
Fiji => 1.9600000000000002
Somalia => 0.0
Lebanon => 3.94
Morocco => 0.7
Albania => 1.73
Kuwait => 0.0
Cuba => 4.37
Haiti => 5.81
Honduras => 2.15
Austria => 13.9
Guinea-Bissau => 2.67
Central African Republic => 2.5199999999999996
Slovenia => 12.969999999999999
Belaru

In [230]:
max = 0 
max_pay=None
for pays in totals:
    if( totals[pays]>max):
        max = totals[pays]
        max_pay = pays
    
print(max_pay,"==>",max)

Hungary ==> 16.29


In [11]:
import pandas as pd 

In [33]:
df1 = pd.read_csv("original.csv")
df1.head()

Year       WHO region                Country Beverage Types  Display Value
0  1986  Western Pacific               Viet Nam           Wine           0.00
1  1986         Americas                Uruguay          Other           0.50
2  1985           Africa           Cte d'Ivoire           Wine           1.62
3  1986         Americas               Colombia           Beer           4.27
4  1987         Americas  Saint Kitts and Nevis           Beer           1.98

In [21]:
world_alcohol[world_alcohol[:,-1] == "1.62"]

array([['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1984', 'Europe', 'Norway', 'Spirits', '1.62'],
       ['1985', 'Western Pacific', 'Philippines', 'Beer', '1.62'],
       ['1985', 'Western Pacific', 'Japan', 'Other', '1.62'],
       ['1985', 'Europe', 'Italy', 'Spirits', '1.62'],
       ['1989', 'Africa', 'South Africa', 'Other', '1.62']], dtype='<U75')

In [32]:
world_alcohol[world_alcohol[:,4]==""] 

(222, 5)

In [34]:
df1.isnull().sum()

Year                0
WHO region          0
Country             0
Beverage Types      0
Display Value     222
dtype: int64

In [36]:
algeria_and_1986 = world_alcohol[(world_alcohol[:,2]=="Algeria")&(world_alcohol[:,0]=="1986")&((world_alcohol[:,3]=="Wine"))]
algeria_and_1986

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1']], dtype='<U75')

In [4]:
 world_alcohol['WHO region']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [22]:
my_array = np.loadtxt('original.csv',delimiter=",",dtype="U75")

In [30]:
def trouve_col(nom,df): 
    i=0
    for i in range(len(df[0])):
            if(df[0][i]==nom):
                          break 
    return df[:,i]


In [31]:
trouve_col("Year",world_alcohol)

array(['Year', '1986', '1986', ..., '1986', '1987', '1986'], dtype='<U75')