Introduction à Numpy

In [2]:
liste_liste = [["grenoble",38],["lyon",69]]

# les tableau avec numpy

In [3]:
import numpy as np

In [4]:
vector=np.array([5,3,9,55])

In [5]:
print(vector)

[ 5  3  9 55]


In [6]:
matrix=np.array([[5,3,9,55],[54,96,4,3]])

In [7]:
print(matrix)

[[ 5  3  9 55]
 [54 96  4  3]]


In [8]:
print(vector.shape)

(4,)


c'est un vecteur de taille 4

In [9]:
print(matrix.shape)

(2, 4)


C'est une matrice de 2 lignes et 4 colonnes 

In [10]:
vec = np.array([10,20,30])

In [11]:
print(vec.shape)

(3,)


In [12]:
mat = np.array([[10,20,30],[5,6,4],[945,6,874]])


In [13]:
print(mat.shape)

(3, 3)


# Lire un data set avec numpy 

In [63]:
import numpy as np
df = np.genfromtxt("original.csv",delimiter=",",dtype="U75")
 

In [64]:
df[:,-1:]

array([['Display Value'],
       ['0'],
       ['0.5'],
       ...,
       ['2.54'],
       ['0'],
       ['5.15']], dtype='<U75')

In [95]:
#la 1ere et 3 colonne + 3 et 5e ligne 
df[:,[x for x in range(df.shape[1]) if(x < 2 and x > 0 ) and (x < 5 and x > 3 )]]


array([], shape=(3258, 0), dtype='<U75')

In [92]:
df[[x for x in range(df.shape[1]) if (x != 2 and x != 3) ],[x for x in range(df.shape[1]) if (x != 2 and x != 3) ]]


array([['Year', 'WHO region', 'Country', 'Beverage Types',
        'Display Value'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1986', 'Americas', 'Colombia', 'Beer', '4.27']], dtype='<U75')

# Afficher les données correctement

In [53]:
world_alcohol

array([[      nan,       nan,       nan,       nan,       nan],
       [1.986e+03,       nan,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan,       nan, 5.000e-01],
       ...,
       [1.986e+03,       nan,       nan,       nan, 2.540e+00],
       [1.987e+03,       nan,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan,       nan, 5.150e+00]])

In [16]:
world_alcohol = np.genfromtxt("original.csv",delimiter=",",dtype="U75" )
world_alcohol

array([['Year', 'WHO region', 'Country', 'Beverage Types',
        'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

# Extraire une valeur depuis un tableau Numpy

In [17]:
matrix=np.array([[5,3,9,55],[54,96,4,3]])

print(matrix)

[[ 5  3  9 55]
 [54 96  4  3]]


In [18]:
liste = matrix [1]
print(liste)

[54 96  4  3]


In [19]:
print(matrix[1][2])
print(liste[2])

4
4


In [20]:
print(matrix[1,2])

4


In [21]:
ivoirien = world_alcohol[3][4]
second_contry = world_alcohol[2][2]
print(ivoirien)
print(second_contry)

1.62
Uruguay


# Extraire un vecteur de valeurs depuis un tableau Numpy

In [22]:
vector=np.array([5,3,9,55])
vector[0:3]

array([5, 3, 9])

In [23]:
matrix=np.array([[5,3,9,55],[54,96,4,3],[54,6,2,9]])
matrix

array([[ 5,  3,  9, 55],
       [54, 96,  4,  3],
       [54,  6,  2,  9]])

In [24]:
matrix[:,1]

array([ 3, 96,  6])

Les deux points veut dire qu'on selectionne toutes les lignes 

In [25]:
matrix[2,:]

array([54,  6,  2,  9])

Les deux points veut dire qu'on selectionne toutes les colonnes 

In [26]:
matrix[1:3,1]

array([96,  6])

In [27]:
contries = world_alcohol[:,2]
alcohol_consumption = world_alcohol[:,4]

contries
 

array(['Country', 'Viet Nam', 'Uruguay', ..., 'Switzerland',
       'Papua New Guinea', 'Swaziland'], dtype='<U75')

In [28]:
alcohol_consumption

array(['Display Value', '0', '0.5', ..., '2.54', '0', '5.15'],
      dtype='<U75')

# Extraire un tableau de valeurs depuis un tableau Numpy

In [29]:
matrix

array([[ 5,  3,  9, 55],
       [54, 96,  4,  3],
       [54,  6,  2,  9]])

In [31]:
matrix[:,0:2]

array([[ 5,  3],
       [54, 96],
       [54,  6]])

In [34]:
matrix[1:3,:]

array([[54, 96,  4,  3],
       [54,  6,  2,  9]])

In [35]:
matrix[1:3,0:2]

array([[54, 96],
       [54,  6]])

In [43]:
first_two_columns= world_alcohol[:,0:2]
first_two_columns

array([['Year', 'WHO region'],
       ['1986', 'Western Pacific'],
       ['1986', 'Americas'],
       ...,
       ['1986', 'Europe'],
       ['1987', 'Western Pacific'],
       ['1986', 'Africa']], dtype='<U75')

toutes les lignes des deux premieres colonnes 

In [49]:
first_ten_years= world_alcohol[0:10,0]
first_ten_years
print(first_ten_years)

['Year' '1986' '1986' '1985' '1986' '1987' '1987' '1987' '1985' '1986']


In [47]:
first_ten_rows= world_alcohol[0:10,:]
first_ten_rows

array([['Year', 'WHO region', 'Country', 'Beverage Types',
        'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
       ['1987', 'Americas', 'Saint Kitts and Nevis', 'Beer', '1.98'],
       ['1987', 'Americas', 'Guatemala', 'Other', '0'],
       ['1987', 'Africa', 'Mauritius', 'Wine', '0.13'],
       ['1985', 'Africa', 'Angola', 'Spirits', '0.39'],
       ['1986', 'Americas', 'Antigua and Barbuda', 'Spirits', '1.55']],
      dtype='<U75')

In [48]:
first_twenty_region= world_alcohol[0:20,1:3]
first_twenty_region

array([['WHO region', 'Country'],
       ['Western Pacific', 'Viet Nam'],
       ['Americas', 'Uruguay'],
       ['Africa', "Cte d'Ivoire"],
       ['Americas', 'Colombia'],
       ['Americas', 'Saint Kitts and Nevis'],
       ['Americas', 'Guatemala'],
       ['Africa', 'Mauritius'],
       ['Africa', 'Angola'],
       ['Americas', 'Antigua and Barbuda'],
       ['Africa', 'Nigeria'],
       ['Africa', 'Botswana'],
       ['Americas', 'Guatemala'],
       ['Western Pacific', "Lao People's Democratic Republic"],
       ['Eastern Mediterranean', 'Afghanistan'],
       ['Western Pacific', 'Viet Nam'],
       ['Africa', 'Guinea-Bissau'],
       ['Americas', 'Costa Rica'],
       ['Africa', 'Seychelles'],
       ['Europe', 'Norway']], dtype='<U75')